#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#define MAX_key 256 // maximum size of key allowed in bytes
#define TABLE_SIZE 10


//separate chaining

// creating the struct of type data
typedef struct data{
    char key[MAX_key];
    int value;
    struct data *next;
} data;

data *hash_table[TABLE_SIZE]; // an array of pointers of type struct data [the array size is 10]

// The function generates the hash value for the given input
unsigned int hash(char *key){
    int length = strnlen(key, MAX_key); // get the length of the input string
    unsigned int hash_value = 0;
    for (int i = 0; i < length; i++){ // loop through every character of the string
        hash_value += key[i];  // adding the value of each character to the hash_value
        // the added hash_values are multiplied by the value of the character and mod by the size of the hash table
        hash_value = (hash_value * key[i]) % TABLE_SIZE;
    }
    return hash_value;
}

// The function initialize the hash table
void initHashTable(){
    for (int i = 0; i < TABLE_SIZE; i++){   // the loop will run until the defined table size is reach
        hash_table[i] = NULL; // each index of the array is assigned by null
    }
}

// This function prints the key, value pairs to the console
void print_table(){
    printf("===========================\n");
    printf("Element\t\tKey-Value\n\n");
    for (int i=0; i < TABLE_SIZE; i++){ // the loop goes through the table
        printf("%i\t\t", i); // prints the element
        if(hash_table[i] == NULL){  // if the element is empty
            printf("---");
        }else{

            data *temp = hash_table[i]; // creates a temporary pointer that points to elements of the hash table
            // when the temp pointer is pointing to an element that is not null which means not empty
            // the while loop will be executed and it will get inside separate links and loop through them as well until the end of those links
            while (temp != NULL){
                printf("%s (%d) -> ", temp->key,temp->value); // prints the key
                //printf("\t\t%d\n", temp->value); // prints the value
                temp = temp->next; // the temp pointer will be pointed to the next node
                // the pointing of nodes will not affect the for loop temp location since, it is always pointed to the next element of the table before
                // the while loop begins
            }
        }
        printf("\n");
    }
    printf("\n\n");
}

// This function insert elements into the hash table
bool insert(data *p){
    if(p == NULL) return NULL; // if the given element is null
    int index = hash(p->key); // the hash value is returned by the hash_function for the given key of the element
    p->next = hash_table[index]; // the link is created between the node and the hash table
    hash_table[index] = p;
    return true;
}

// this function find an element by its key value
data *search(char *key){
    int index = hash(key); // generate the hash value based on the key
    data *temp = hash_table[index]; // temporary pointer is created and pointed to the index value of the table, generated by the hash function
    // while the temp pointer is not null and the key values are matching, the loop will continue
    // which means the while loop is going through the separate nodes of the selected index position
    while(temp != NULL && strncmp(temp->key, key, MAX_key) != 0){
        temp = temp->next; // temp is pointed to the next node
    }
    return temp;
}

// The function deletes an element based on the key value
data *deleteItem(char *key){
    int index = hash(key); // generate the hash value
    data *temp = hash_table[index];  // the temp pointer is pointing to the element by the index of the hash value
    data *previous = NULL;
    while(temp != NULL && strncmp(temp->key, key, MAX_key) != 0){
        previous = temp;
        temp = temp->next;
    }
    if(temp == NULL) return NULL;
    if(previous == NULL){
        // previous node null means, the above while loop didn't run and we are on the first node of the list
        hash_table[index] = temp->next; // making it null
    }else{
        previous->next = temp->next;
    }
    return temp;
}

int main()
{
    initHashTable();

    data laptop = {.key = "laptop", .value = 2000};
    data laptop2 = {.key = "laptop", .value = 2300}; // a new entry with similar key value to test chaining
    data phone = {.key = "phone", .value = 1000};
    data tab = {.key = "tab", .value = 750};
    data desktop = {.key = "desktop", .value = 2500};

    insert(&laptop);
    insert(&phone);
    insert(&tab);
    insert(&desktop);
    insert(&laptop2);

    print_table();

    deleteItem("desktop");


    data *lookupkey = search("laptop");
    if(lookupkey == NULL){
        printf("\ndata not found!\n");
    }else{
        printf("Found %s.\n", lookupkey->key);
    }

    print_table();

    return 0;
}
